from __future__ import annotations


def demo_payload() -> dict:
    return {
        "events": {
            "pulse-demo-001": {
                "id": "pulse-demo-001",
                "title": "Cierre preventivo de vía tras reporte de deslizamiento",
                "summary": "Varias fuentes reportan bloqueo parcial y equipos municipales en verificación.",
                "description": "Se detectan reportes coincidentes sobre un posible deslizamiento con afectación de movilidad.",
                "category": "emergencias",
                "location": "Quito, Ecuador",
                "first_seen": "2026-08-20T13:18:00+00:00",
                "last_seen": "2026-08-20T13:42:00+00:00",
                "status": "En corroboración",
                "priority": "IMPORTANTE",
                "confidence_score": 74,
                "source_count": 4,
                "official_source_count": 1,
                "signal_count": 7,
                "tags": ["movilidad", "emergencia", "municipio"],
                "keywords": ["deslizamiento", "cierre vial", "lluvias"],
                "evolution": [
                    "13:18 Primera señal detectada en medio local.",
                    "13:27 Dos fuentes independientes reportan congestión.",
                    "13:42 Cuenta municipal informa evaluación en sitio.",
                ],
                "pulse_conclusion": "Evento en corroboración con señal oficial inicial. Requiere confirmación operativa antes de elevar a urgente.",
                "information": "No hay reporte confirmado de víctimas en las señales disponibles.",
                "followed": True,
            },
            "pulse-demo-002": {
                "id": "pulse-demo-002",
                "title": "Convocatoria ciudadana frente a entidad pública",
                "summary": "Monitores sociales detectan convocatoria con crecimiento moderado de menciones.",
                "description": "La conversación aumenta, pero todavía depende de pocas fuentes originales.",
                "category": "política",
                "location": "Guayaquil, Ecuador",
                "first_seen": "2026-08-20T12:05:00+00:00",
                "last_seen": "2026-08-20T13:20:00+00:00",
                "status": "En observación",
                "priority": "SEGUIMIENTO",
                "confidence_score": 48,
                "source_count": 2,
                "official_source_count": 0,
                "signal_count": 11,
                "tags": ["ciudadanía", "política"],
                "keywords": ["convocatoria", "plantón"],
                "evolution": ["12:05 Señal inicial.", "13:20 Aumentan menciones replicadas."],
                "pulse_conclusion": "Mantener monitoreo. La mayoría de menciones son réplicas del mismo origen.",
            },
            "pulse-demo-003": {
                "id": "pulse-demo-003",
                "title": "Alerta meteorológica por lluvias intensas",
                "summary": "Fuente oficial publica alerta y medios regionales replican recomendaciones.",
                "description": "Confirmación oficial disponible con cobertura de medios regionales.",
                "category": "clima",
                "location": "Manabí, Ecuador",
                "first_seen": "2026-08-20T11:48:00+00:00",
                "last_seen": "2026-08-20T13:11:00+00:00",
                "status": "Confirmado",
                "priority": "URGENTE",
                "confidence_score": 91,
                "source_count": 5,
                "official_source_count": 2,
                "signal_count": 9,
                "tags": ["clima", "oficial", "riesgo"],
                "keywords": ["lluvias", "alerta", "inundaciones"],
                "evolution": ["11:48 Boletín oficial.", "12:30 Medios regionales amplían.", "13:11 Nueva actualización oficial."],
                "pulse_conclusion": "Evento confirmado por fuente oficial. Priorizar alerta editorial y seguimiento de afectaciones.",
                "information": "Monitorear reportes de tránsito, cortes eléctricos y COE local.",
            },
        },
        "signals": {
            "sig-demo-001": {
                "id": "sig-demo-001",
                "event_id": "pulse-demo-001",
                "source": "Municipio",
                "source_type": "oficial",
                "source_id": "src-demo-oficial",
                "text": "Equipo de movilidad evalúa cierre vial preventivo por material en calzada.",
                "location": "Quito, Ecuador",
                "keywords": ["cierre vial", "deslizamiento"],
                "reliability": 88,
                "raw_payload_hash": "demo-001",
            }
        },
        "sources": {
            "src-demo-oficial": {
                "id": "src-demo-oficial",
                "name": "Municipio",
                "platform": "oficial",
                "type": "oficial",
                "url": "https://example.local/oficial",
                "reputation": 88,
                "historical_reliability": 82,
                "priority": "alta",
                "active": True,
            }
        },
        "x_usage": [],
    }
