"""Preview watermark module for LENS."""

PREVIEW_WATERMARK_VERSION = "2.0"
SUPPORTED_WATERMARK_TEMPLATES = ("xinhua",)
SUPPORTED_OUTPUT_FORMATS = ("jpg",)
SUPPORTED_OUTPUT_RESOLUTIONS = (2000, 2500, 3000)
